# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrei/projects/cmpcfgs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrei/projects/cmpcfgs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrei/projects/cmpcfgs/CMakeFiles /Users/andrei/projects/cmpcfgs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrei/projects/cmpcfgs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmpcfgs

# Build rule for target.
cmpcfgs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmpcfgs
.PHONY : cmpcfgs

# fast build rule for target.
cmpcfgs/fast:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/build
.PHONY : cmpcfgs/fast

src/CFG.o: src/CFG.cpp.o

.PHONY : src/CFG.o

# target to build an object file
src/CFG.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CFG.cpp.o
.PHONY : src/CFG.cpp.o

src/CFG.i: src/CFG.cpp.i

.PHONY : src/CFG.i

# target to preprocess a source file
src/CFG.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CFG.cpp.i
.PHONY : src/CFG.cpp.i

src/CFG.s: src/CFG.cpp.s

.PHONY : src/CFG.s

# target to generate assembly for a file
src/CFG.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CFG.cpp.s
.PHONY : src/CFG.cpp.s

src/CFGsContainer.o: src/CFGsContainer.cpp.o

.PHONY : src/CFGsContainer.o

# target to build an object file
src/CFGsContainer.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CFGsContainer.cpp.o
.PHONY : src/CFGsContainer.cpp.o

src/CFGsContainer.i: src/CFGsContainer.cpp.i

.PHONY : src/CFGsContainer.i

# target to preprocess a source file
src/CFGsContainer.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CFGsContainer.cpp.i
.PHONY : src/CFGsContainer.cpp.i

src/CFGsContainer.s: src/CFGsContainer.cpp.s

.PHONY : src/CFGsContainer.s

# target to generate assembly for a file
src/CFGsContainer.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CFGsContainer.cpp.s
.PHONY : src/CFGsContainer.cpp.s

src/CfgData.o: src/CfgData.cpp.o

.PHONY : src/CfgData.o

# target to build an object file
src/CfgData.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CfgData.cpp.o
.PHONY : src/CfgData.cpp.o

src/CfgData.i: src/CfgData.cpp.i

.PHONY : src/CfgData.i

# target to preprocess a source file
src/CfgData.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CfgData.cpp.i
.PHONY : src/CfgData.cpp.i

src/CfgData.s: src/CfgData.cpp.s

.PHONY : src/CfgData.s

# target to generate assembly for a file
src/CfgData.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CfgData.cpp.s
.PHONY : src/CfgData.cpp.s

src/CfgNode.o: src/CfgNode.cpp.o

.PHONY : src/CfgNode.o

# target to build an object file
src/CfgNode.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CfgNode.cpp.o
.PHONY : src/CfgNode.cpp.o

src/CfgNode.i: src/CfgNode.cpp.i

.PHONY : src/CfgNode.i

# target to preprocess a source file
src/CfgNode.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CfgNode.cpp.i
.PHONY : src/CfgNode.cpp.i

src/CfgNode.s: src/CfgNode.cpp.s

.PHONY : src/CfgNode.s

# target to generate assembly for a file
src/CfgNode.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/CfgNode.cpp.s
.PHONY : src/CfgNode.cpp.s

src/Instruction.o: src/Instruction.cpp.o

.PHONY : src/Instruction.o

# target to build an object file
src/Instruction.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/Instruction.cpp.o
.PHONY : src/Instruction.cpp.o

src/Instruction.i: src/Instruction.cpp.i

.PHONY : src/Instruction.i

# target to preprocess a source file
src/Instruction.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/Instruction.cpp.i
.PHONY : src/Instruction.cpp.i

src/Instruction.s: src/Instruction.cpp.s

.PHONY : src/Instruction.s

# target to generate assembly for a file
src/Instruction.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/Instruction.cpp.s
.PHONY : src/Instruction.cpp.s

src/SimpleStrategy.o: src/SimpleStrategy.cpp.o

.PHONY : src/SimpleStrategy.o

# target to build an object file
src/SimpleStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/SimpleStrategy.cpp.o
.PHONY : src/SimpleStrategy.cpp.o

src/SimpleStrategy.i: src/SimpleStrategy.cpp.i

.PHONY : src/SimpleStrategy.i

# target to preprocess a source file
src/SimpleStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/SimpleStrategy.cpp.i
.PHONY : src/SimpleStrategy.cpp.i

src/SimpleStrategy.s: src/SimpleStrategy.cpp.s

.PHONY : src/SimpleStrategy.s

# target to generate assembly for a file
src/SimpleStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/SimpleStrategy.cpp.s
.PHONY : src/SimpleStrategy.cpp.s

src/SpecificStrategy.o: src/SpecificStrategy.cpp.o

.PHONY : src/SpecificStrategy.o

# target to build an object file
src/SpecificStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/SpecificStrategy.cpp.o
.PHONY : src/SpecificStrategy.cpp.o

src/SpecificStrategy.i: src/SpecificStrategy.cpp.i

.PHONY : src/SpecificStrategy.i

# target to preprocess a source file
src/SpecificStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/SpecificStrategy.cpp.i
.PHONY : src/SpecificStrategy.cpp.i

src/SpecificStrategy.s: src/SpecificStrategy.cpp.s

.PHONY : src/SpecificStrategy.s

# target to generate assembly for a file
src/SpecificStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/SpecificStrategy.cpp.s
.PHONY : src/SpecificStrategy.cpp.s

src/Strategy.o: src/Strategy.cpp.o

.PHONY : src/Strategy.o

# target to build an object file
src/Strategy.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/Strategy.cpp.o
.PHONY : src/Strategy.cpp.o

src/Strategy.i: src/Strategy.cpp.i

.PHONY : src/Strategy.i

# target to preprocess a source file
src/Strategy.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/Strategy.cpp.i
.PHONY : src/Strategy.cpp.i

src/Strategy.s: src/Strategy.cpp.s

.PHONY : src/Strategy.s

# target to generate assembly for a file
src/Strategy.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/Strategy.cpp.s
.PHONY : src/Strategy.cpp.s

src/cmpcfgs.o: src/cmpcfgs.cpp.o

.PHONY : src/cmpcfgs.o

# target to build an object file
src/cmpcfgs.cpp.o:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/cmpcfgs.cpp.o
.PHONY : src/cmpcfgs.cpp.o

src/cmpcfgs.i: src/cmpcfgs.cpp.i

.PHONY : src/cmpcfgs.i

# target to preprocess a source file
src/cmpcfgs.cpp.i:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/cmpcfgs.cpp.i
.PHONY : src/cmpcfgs.cpp.i

src/cmpcfgs.s: src/cmpcfgs.cpp.s

.PHONY : src/cmpcfgs.s

# target to generate assembly for a file
src/cmpcfgs.cpp.s:
	$(MAKE) -f CMakeFiles/cmpcfgs.dir/build.make CMakeFiles/cmpcfgs.dir/src/cmpcfgs.cpp.s
.PHONY : src/cmpcfgs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cmpcfgs"
	@echo "... src/CFG.o"
	@echo "... src/CFG.i"
	@echo "... src/CFG.s"
	@echo "... src/CFGsContainer.o"
	@echo "... src/CFGsContainer.i"
	@echo "... src/CFGsContainer.s"
	@echo "... src/CfgData.o"
	@echo "... src/CfgData.i"
	@echo "... src/CfgData.s"
	@echo "... src/CfgNode.o"
	@echo "... src/CfgNode.i"
	@echo "... src/CfgNode.s"
	@echo "... src/Instruction.o"
	@echo "... src/Instruction.i"
	@echo "... src/Instruction.s"
	@echo "... src/SimpleStrategy.o"
	@echo "... src/SimpleStrategy.i"
	@echo "... src/SimpleStrategy.s"
	@echo "... src/SpecificStrategy.o"
	@echo "... src/SpecificStrategy.i"
	@echo "... src/SpecificStrategy.s"
	@echo "... src/Strategy.o"
	@echo "... src/Strategy.i"
	@echo "... src/Strategy.s"
	@echo "... src/cmpcfgs.o"
	@echo "... src/cmpcfgs.i"
	@echo "... src/cmpcfgs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

